import type { Vocab } from "@zenith-jp/core";

export const lesson10Vocab: Vocab[] = [
    {
        id: "1",
        lessonId: "lesson_10",
        kana: "あります",
        kanji: "",
        meaning: "Có (đồ vật, thực vật)",
        romaji: "arimasu",
        clusterId: "c1",
        iconName: "package",
    },

    {
        id: "2",
        lessonId: "lesson_10",
        kana: "います",
        kanji: "",
        meaning: "Có (người, động vật)",
        romaji: "imasu",
        clusterId: "c1",
        iconName: "users",
    },

    {
        id: "3",
        lessonId: "lesson_10",
        kana: "いろいろ",
        kanji: "",
        meaning: "Nhiều, đa dạng",
        romaji: "iroiro",
        clusterId: "c1",
        iconName: "sparkles",
    },

    {
        id: "4",
        lessonId: "lesson_10",
        kana: "もの",
        kanji: "物",
        meaning: "Đồ vật, thứ",
        romaji: "mono",
        clusterId: "c1",
        iconName: "box",
    },

    {
        id: "5",
        lessonId: "lesson_10",
        kana: "き",
        kanji: "木",
        meaning: "Cây",
        romaji: "ki",
        clusterId: "c1",
        iconName: "tree-pine",
    },

    {
        id: "6",
        lessonId: "lesson_10",
        kana: "でんち",
        kanji: "電池",
        meaning: "Pin",
        romaji: "denchi",
        clusterId: "c1",
        iconName: "battery",
    },

    {
        id: "7",
        lessonId: "lesson_10",
        kana: "はこ",
        kanji: "箱",
        meaning: "Cái hộp",
        romaji: "hako",
        clusterId: "c1",
        iconName: "package-open",
    },

    {
        id: "8",
        lessonId: "lesson_10",
        kana: "スイッチ",
        kanji: "",
        meaning: "Công tắc",
        romaji: "suicchi",
        clusterId: "c1",
        iconName: "toggle-left",
    },

    {
        id: "9",
        lessonId: "lesson_10",
        kana: "れいぞうこ",
        kanji: "冷蔵庫",
        meaning: "Tủ lạnh",
        romaji: "reizouko",
        clusterId: "c1",
        iconName: "refrigerator",
    },

    {
        id: "10",
        lessonId: "lesson_10",
        kana: "テーブル",
        kanji: "",
        meaning: "Cái bàn",
        romaji: "teeburu",
        clusterId: "c1",
        iconName: "table",
    },

    {
        id: "11",
        lessonId: "lesson_10",
        kana: "おとこのひと",
        kanji: "男の人",
        meaning: "Người đàn ông",
        romaji: "otoko no hito",
        clusterId: "c2",
        iconName: "user",
    },

    {
        id: "12",
        lessonId: "lesson_10",
        kana: "おんなのひと",
        kanji: "女の人",
        meaning: "Người phụ nữ",
        romaji: "onna no hito",
        clusterId: "c2",
        iconName: "user-round",
    },

    {
        id: "13",
        lessonId: "lesson_10",
        kana: "おとこのこ",
        kanji: "男の子",
        meaning: "Bé trai",
        romaji: "otoko no ko",
        clusterId: "c2",
        iconName: "baby",
    },

    {
        id: "14",
        lessonId: "lesson_10",
        kana: "おんなのこ",
        kanji: "女の子",
        meaning: "Bé gái",
        romaji: "onna no ko",
        clusterId: "c2",
        iconName: "baby",
    },

    {
        id: "15",
        lessonId: "lesson_10",
        kana: "いぬ",
        kanji: "犬",
        meaning: "Con chó",
        romaji: "inu",
        clusterId: "c2",
        iconName: "dog",
    },

    {
        id: "16",
        lessonId: "lesson_10",
        kana: "ねこ",
        kanji: "猫",
        meaning: "Con mèo",
        romaji: "neko",
        clusterId: "c2",
        iconName: "cat",
    },

    {
        id: "17",
        lessonId: "lesson_10",
        kana: "パンダ",
        kanji: "",
        meaning: "Con gấu trúc",
        romaji: "panda",
        clusterId: "c2",
        iconName: "paw-print",
    },

    {
        id: "18",
        lessonId: "lesson_10",
        kana: "ぞう",
        kanji: "象",
        meaning: "Con voi",
        romaji: "zou",
        clusterId: "c2",
        iconName: "paw-print",
    },

    {
        id: "19",
        lessonId: "lesson_10",
        kana: "ベッド",
        kanji: "",
        meaning: "Cái giường",
        romaji: "beddo",
        clusterId: "c2",
        iconName: "bed",
    },

    {
        id: "20",
        lessonId: "lesson_10",
        kana: "たな",
        kanji: "棚",
        meaning: "Cái kệ",
        romaji: "tana",
        clusterId: "c2",
        iconName: "shelves",
    },

    {
        id: "21",
        lessonId: "lesson_10",
        kana: "ドア",
        kanji: "",
        meaning: "Cửa ra vào",
        romaji: "doa",
        clusterId: "c3",
        iconName: "door-open",
    },

    {
        id: "22",
        lessonId: "lesson_10",
        kana: "まど",
        kanji: "窓",
        meaning: "Cửa sổ",
        romaji: "mado",
        clusterId: "c3",
        iconName: "square",
    },

    {
        id: "23",
        lessonId: "lesson_10",
        kana: "ポスト",
        kanji: "",
        meaning: "Hộp thư",
        romaji: "posuto",
        clusterId: "c3",
        iconName: "mailbox",
    },

    {
        id: "24",
        lessonId: "lesson_10",
        kana: "ビル",
        kanji: "",
        meaning: "Tòa nhà",
        romaji: "biru",
        clusterId: "c3",
        iconName: "building",
    },

    {
        id: "25",
        lessonId: "lesson_10",
        kana: "こうえん",
        kanji: "公園",
        meaning: "Công viên",
        romaji: "kouen",
        clusterId: "c3",
        iconName: "trees",
    },

    {
        id: "26",
        lessonId: "lesson_10",
        kana: "きっさてん",
        kanji: "喫茶店",
        meaning: "Quán cà phê",
        romaji: "kissaten",
        clusterId: "c3",
        iconName: "coffee",
    },

    {
        id: "27",
        lessonId: "lesson_10",
        kana: "ほんや",
        kanji: "本屋",
        meaning: "Tiệm sách",
        romaji: "honya",
        clusterId: "c3",
        iconName: "book-open",
    },

    {
        id: "28",
        lessonId: "lesson_10",
        kana: "～や",
        kanji: "～屋",
        meaning: "Tiệm, cửa hàng",
        romaji: "~ya",
        clusterId: "c3",
        iconName: "store",
    },

    {
        id: "29",
        lessonId: "lesson_10",
        kana: "のりば",
        kanji: "乗り場",
        meaning: "Bến xe",
        romaji: "noriba",
        clusterId: "c3",
        iconName: "bus",
    },

    {
        id: "30",
        lessonId: "lesson_10",
        kana: "けん",
        kanji: "県",
        meaning: "Tỉnh",
        romaji: "ken",
        clusterId: "c3",
        iconName: "map",
    },

    {
        id: "31",
        lessonId: "lesson_10",
        kana: "うえ",
        kanji: "上",
        meaning: "Trên",
        romaji: "ue",
        clusterId: "c4",
        iconName: "arrow-up",
    },

    {
        id: "32",
        lessonId: "lesson_10",
        kana: "した",
        kanji: "下",
        meaning: "Dưới",
        romaji: "shita",
        clusterId: "c4",
        iconName: "arrow-down",
    },

    {
        id: "33",
        lessonId: "lesson_10",
        kana: "まえ",
        kanji: "前",
        meaning: "Trước",
        romaji: "mae",
        clusterId: "c4",
        iconName: "move-up",
    },

    {
        id: "34",
        lessonId: "lesson_10",
        kana: "うしろ",
        kanji: "後ろ",
        meaning: "Sau",
        romaji: "ushiro",
        clusterId: "c4",
        iconName: "move-down",
    },

    {
        id: "35",
        lessonId: "lesson_10",
        kana: "みぎ",
        kanji: "右",
        meaning: "Phải",
        romaji: "migi",
        clusterId: "c4",
        iconName: "arrow-right",
    },

    {
        id: "36",
        lessonId: "lesson_10",
        kana: "ひだり",
        kanji: "左",
        meaning: "Trái",
        romaji: "hidari",
        clusterId: "c4",
        iconName: "arrow-left",
    },

    {
        id: "37",
        lessonId: "lesson_10",
        kana: "なか",
        kanji: "中",
        meaning: "Trong",
        romaji: "naka",
        clusterId: "c4",
        iconName: "square-dashed",
    },

    {
        id: "38",
        lessonId: "lesson_10",
        kana: "そと",
        kanji: "外",
        meaning: "Ngoài",
        romaji: "soto",
        clusterId: "c4",
        iconName: "square",
    },

    {
        id: "39",
        lessonId: "lesson_10",
        kana: "となり",
        kanji: "隣",
        meaning: "Bên cạnh",
        romaji: "tonari",
        clusterId: "c4",
        iconName: "columns-2",
    },

    {
        id: "40",
        lessonId: "lesson_10",
        kana: "ちかく",
        kanji: "近く",
        meaning: "Gần",
        romaji: "chikaku",
        clusterId: "c4",
        iconName: "map-pin",
    },

    {
        id: "41",
        lessonId: "lesson_10",
        kana: "あいだ",
        kanji: "間",
        meaning: "Ở giữa",
        romaji: "aida",
        clusterId: "c5",
        iconName: "separator-horizontal",
    },

    {
        id: "42",
        lessonId: "lesson_10",
        kana: "かど",
        kanji: "角",
        meaning: "Góc",
        romaji: "kado",
        clusterId: "c5",
        iconName: "corner-down-right",
    },

    {
        id: "43",
        lessonId: "lesson_10",
        kana: "エリア",
        kanji: "",
        meaning: "Khu vực",
        romaji: "eria",
        clusterId: "c5",
        iconName: "map",
    },

    {
        id: "44",
        lessonId: "lesson_10",
        kana: "いちばんした",
        kanji: "一番下",
        meaning: "Ở dưới cùng",
        romaji: "ichiban shita",
        clusterId: "c5",
        iconName: "chevrons-down",
    },

    {
        id: "45",
        lessonId: "lesson_10",
        kana: "ナンプラー",
        kanji: "",
        meaning: "Nước mắm",
        romaji: "nanpuraa",
        clusterId: "c5",
        iconName: "flask-conical",
    },

    {
        id: "46",
        lessonId: "lesson_10",
        kana: "まんなか",
        kanji: "真ん中",
        meaning: "Chính giữa",
        romaji: "mannaka",
        clusterId: "c6",
        iconName: "circle-dot",
    },

    {
        id: "47",
        lessonId: "lesson_10",
        kana: "ちず",
        kanji: "地図",
        meaning: "Bản đồ",
        romaji: "chizu",
        clusterId: "c6",
        iconName: "map-pinned",
    },

    {
        id: "48",
        lessonId: "lesson_10",
        kana: "ばしょ",
        kanji: "場所",
        meaning: "Địa điểm",
        romaji: "basho",
        clusterId: "c6",
        iconName: "map-pin-house",
    },

    {
        id: "49",
        lessonId: "lesson_10",
        kana: "ところ",
        kanji: "所",
        meaning: "Nơi chốn",
        romaji: "tokoro",
        clusterId: "c6",
        iconName: "navigation",
    },
];