import type { Vocab } from "@zenith-jp/core";

export const lesson8Vocab: Vocab[] = [
    {
        id: "1",
        lessonId: "lesson_8",
        kana: "みにくい",
        meaning: "Xấu",
        romaji: "minikui",
        clusterId: "c1",
        iconName: "frown",
    },
    {
        id: "2",
        lessonId: "lesson_8",
        kana: "ハンサム(な)",
        meaning: "Đẹp trai",
        romaji: "hansamu",
        clusterId: "c1",
        iconName: "sparkles",
    },
    {
        id: "3",
        lessonId: "lesson_8",
        kana: "きれい(な)",
        meaning: "(Cảnh) đẹp, đẹp, sạch",
        romaji: "kirei",
        clusterId: "c1",
        iconName: "star",
    },
    {
        id: "4",
        lessonId: "lesson_8",
        kana: "しずか(な)",
        kanji: "静か(な)",
        meaning: "Yên tĩnh",
        romaji: "shizuka",
        clusterId: "c1",
        iconName: "moon",
    },
    {
        id: "5",
        lessonId: "lesson_8",
        kana: "にぎやか(な)",
        kanji: "賑やか(な)",
        meaning: "Nhộn nhịp",
        romaji: "nigiyaka",
        clusterId: "c1",
        iconName: "party-popper",
    },
    {
        id: "6",
        lessonId: "lesson_8",
        kana: "ゆうめい(な)",
        kanji: "有名(な)",
        meaning: "Nổi tiếng",
        romaji: "yuumei",
        clusterId: "c1",
        iconName: "badge-check",
    },
    {
        id: "7",
        lessonId: "lesson_8",
        kana: "しんせつ(な)",
        kanji: "親切(な)",
        meaning: "Tử tế",
        romaji: "shinsetsu",
        clusterId: "c1",
        iconName: "heart-handshake",
    },
    {
        id: "8",
        lessonId: "lesson_8",
        kana: "げんき(な)",
        kanji: "元気(な)",
        meaning: "Khỏe mạnh, năng động",
        romaji: "genki",
        clusterId: "c1",
        iconName: "activity",
    },
    {
        id: "9",
        lessonId: "lesson_8",
        kana: "ひま(な)",
        kanji: "暇(な)",
        meaning: "Rảnh rỗi",
        romaji: "hima",
        clusterId: "c1",
        iconName: "coffee",
    },
    {
        id: "10",
        lessonId: "lesson_8",
        kana: "いそがしい",
        kanji: "忙しい",
        meaning: "Bận rộn",
        romaji: "isogashii",
        clusterId: "c1",
        iconName: "timer",
    },
    {
        id: "11",
        lessonId: "lesson_8",
        kana: "べんり(な)",
        kanji: "便利(な)",
        meaning: "Tiện lợi",
        romaji: "benri",
        clusterId: "c2",
        iconName: "zap",
    },
    {
        id: "12",
        lessonId: "lesson_8",
        kana: "すてき(な)",
        meaning: "Tuyệt vời",
        romaji: "suteki",
        clusterId: "c2",
        iconName: "sparkle",
    },
    {
        id: "13",
        lessonId: "lesson_8",
        kana: "おおきい",
        kanji: "大きい",
        meaning: "To, lớn",
        romaji: "ookii",
        clusterId: "c2",
        iconName: "maximize",
    },
    {
        id: "14",
        lessonId: "lesson_8",
        kana: "ちいさい",
        kanji: "小さい",
        meaning: "Nhỏ, bé",
        romaji: "chiisai",
        clusterId: "c2",
        iconName: "minimize",
    },
    {
        id: "15",
        lessonId: "lesson_8",
        kana: "あたらしい",
        kanji: "新しい",
        meaning: "Mới",
        romaji: "atarashii",
        clusterId: "c2",
        iconName: "package-plus",
    },
    {
        id: "16",
        lessonId: "lesson_8",
        kana: "ふるい",
        kanji: "古い",
        meaning: "Cũ",
        romaji: "furui",
        clusterId: "c2",
        iconName: "archive",
    },
    {
        id: "17",
        lessonId: "lesson_8",
        kana: "いい",
        meaning: "Tốt",
        romaji: "ii",
        clusterId: "c2",
        iconName: "thumbs-up",
    },
    {
        id: "18",
        lessonId: "lesson_8",
        kana: "わるい",
        kanji: "悪い",
        meaning: "Xấu, tệ",
        romaji: "warui",
        clusterId: "c2",
        iconName: "thumbs-down",
    },
    {
        id: "19",
        lessonId: "lesson_8",
        kana: "あつい",
        kanji: "熱い",
        meaning: "Nóng",
        romaji: "atsui",
        clusterId: "c3",
        iconName: "flame",
    },
    {
        id: "20",
        lessonId: "lesson_8",
        kana: "つめたい",
        kanji: "冷たい",
        meaning: "Lạnh",
        romaji: "tsumetai",
        clusterId: "c3",
        iconName: "snowflake",
    },
    {
        id: "21",
        lessonId: "lesson_8",
        kana: "あつい",
        kanji: "暑い",
        meaning: "(Trời) nóng",
        romaji: "atsui",
        clusterId: "c3",
        iconName: "sun",
    },
    {
        id: "22",
        lessonId: "lesson_8",
        kana: "さむい",
        kanji: "寒い",
        meaning: "(Trời) lạnh",
        romaji: "samui",
        clusterId: "c3",
        iconName: "cloud-snow",
    },
    {
        id: "23",
        lessonId: "lesson_8",
        kana: "むずかしい",
        kanji: "難しい",
        meaning: "Khó",
        romaji: "muzukashii",
        clusterId: "c4",
        iconName: "brain",
    },
    {
        id: "24",
        lessonId: "lesson_8",
        kana: "やさしい",
        kanji: "優しい",
        meaning: "Dễ",
        romaji: "yasashii",
        clusterId: "c4",
        iconName: "feather",
    },
    {
        id: "25",
        lessonId: "lesson_8",
        kana: "きびしい",
        meaning: "Nghiêm khắc",
        romaji: "kibishii",
        clusterId: "c4",
        iconName: "shield-alert",
    },
    {
        id: "26",
        lessonId: "lesson_8",
        kana: "やさしい",
        meaning: "Dịu dàng, hiền từ",
        romaji: "yasashii",
        clusterId: "c4",
        iconName: "heart",
    },
    {
        id: "27",
        lessonId: "lesson_8",
        kana: "たかい",
        kanji: "高い",
        meaning: "Đắt",
        romaji: "takai",
        clusterId: "c5",
        iconName: "wallet",
    },
    {
        id: "28",
        lessonId: "lesson_8",
        kana: "やすい",
        kanji: "安い",
        meaning: "Rẻ",
        romaji: "yasui",
        clusterId: "c5",
        iconName: "badge-dollar-sign",
    },
    {
        id: "29",
        lessonId: "lesson_8",
        kana: "ひくい",
        kanji: "低い",
        meaning: "Thấp",
        romaji: "hikui",
        clusterId: "c5",
        iconName: "arrow-down",
    },
    {
        id: "30",
        lessonId: "lesson_8",
        kana: "たかい",
        kanji: "高い",
        meaning: "Cao",
        romaji: "takai",
        clusterId: "c5",
        iconName: "arrow-up",
    },
    {
        id: "31",
        lessonId: "lesson_8",
        kana: "おもしろい",
        meaning: "Thú vị",
        romaji: "omoshiroi",
        clusterId: "c6",
        iconName: "laugh",
    },
    {
        id: "32",
        lessonId: "lesson_8",
        kana: "おいしい",
        meaning: "Ngon",
        romaji: "oishii",
        clusterId: "c6",
        iconName: "utensils",
    },
    {
        id: "33",
        lessonId: "lesson_8",
        kana: "たのしい",
        kanji: "楽しい",
        meaning: "Vui vẻ",
        romaji: "tanoshii",
        clusterId: "c6",
        iconName: "smile",
    },
    {
        id: "34",
        lessonId: "lesson_8",
        kana: "しろい",
        kanji: "白い",
        meaning: "Trắng",
        romaji: "shiroi",
        clusterId: "c6",
        iconName: "circle",
    },
    {
        id: "35",
        lessonId: "lesson_8",
        kana: "くろい",
        kanji: "黒い",
        meaning: "Đen",
        romaji: "kuroi",
        clusterId: "c6",
        iconName: "circle-dot",
    },
    {
        id: "36",
        lessonId: "lesson_8",
        kana: "あかい",
        kanji: "赤い",
        meaning: "Đỏ",
        romaji: "akai",
        clusterId: "c6",
        iconName: "palette",
    },
    {
        id: "37",
        lessonId: "lesson_8",
        kana: "あおい",
        kanji: "青い",
        meaning: "Xanh",
        romaji: "aoi",
        clusterId: "c6",
        iconName: "droplets",
    },
    {
        id: "38",
        lessonId: "lesson_8",
        kana: "さくら",
        kanji: "桜",
        meaning: "Hoa anh đào",
        romaji: "sakura",
        clusterId: "c7",
        iconName: "flower-2",
    },
    {
        id: "39",
        lessonId: "lesson_8",
        kana: "やま",
        kanji: "山",
        meaning: "Núi",
        romaji: "yama",
        clusterId: "c7",
        iconName: "mountain",
    },
    {
        id: "40",
        lessonId: "lesson_8",
        kana: "まち",
        kanji: "町",
        meaning: "Thành phố",
        romaji: "machi",
        clusterId: "c7",
        iconName: "building-2",
    },
    {
        id: "41",
        lessonId: "lesson_8",
        kana: "たべもの",
        kanji: "食べ物",
        meaning: "Thức ăn",
        romaji: "tabemono",
        clusterId: "c7",
        iconName: "sandwich",
    },
    {
        id: "42",
        lessonId: "lesson_8",
        kana: "ところ",
        kanji: "所",
        meaning: "Chỗ, nơi",
        romaji: "tokoro",
        clusterId: "c7",
        iconName: "map-pinned",
    },
    {
        id: "43",
        lessonId: "lesson_8",
        kana: "りょう",
        meaning: "Ký túc xá",
        romaji: "ryou",
        clusterId: "c7",
        iconName: "bed",
    },
    {
        id: "44",
        lessonId: "lesson_8",
        kana: "べんきょう",
        kanji: "勉強",
        meaning: "Học tập",
        romaji: "benkyou",
        clusterId: "c8",
        iconName: "pencil",
    },
    {
        id: "45",
        lessonId: "lesson_8",
        kana: "せいかつ",
        kanji: "生活",
        meaning: "Cuộc sống",
        romaji: "seikatsu",
        clusterId: "c8",
        iconName: "home",
    },
    {
        id: "46",
        lessonId: "lesson_8",
        kana: "(お)しごと",
        kanji: "お仕事",
        meaning: "Công việc",
        romaji: "oshigoto",
        clusterId: "c8",
        iconName: "briefcase-business",
    },
    {
        id: "47",
        lessonId: "lesson_8",
        kana: "どう",
        meaning: "Như thế nào",
        romaji: "dou",
        clusterId: "c8",
        iconName: "message-circle-question",
    },
    {
        id: "48",
        lessonId: "lesson_8",
        kana: "どんな",
        meaning: "~ nào",
        romaji: "donna",
        clusterId: "c8",
        iconName: "list-filter",
    },
    {
        id: "49",
        lessonId: "lesson_8",
        kana: "どれ",
        meaning: "Cái nào",
        romaji: "dore",
        clusterId: "c8",
        iconName: "mouse-pointer-click",
    },
];