import type { Vocab } from "@zenith-jp/core";

export const lesson15Vocab: Vocab[] = [
  {
    id: "1",
    lessonId: "lesson_15",
    kana: "たちます",
    kanji: "立ちます",
    meaning: "Đứng",
    romaji: "tachimasu",
    clusterId: "c1",
    iconName: "person-standing",
  },

  {
    id: "2",
    lessonId: "lesson_15",
    kana: "すわります",
    kanji: "座ります",
    meaning: "Ngồi",
    romaji: "suwarimasu",
    clusterId: "c1",
    iconName: "chair",
  },

  {
    id: "3",
    lessonId: "lesson_15",
    kana: "つかいます",
    kanji: "使います",
    meaning: "Dùng, sử dụng",
    romaji: "tsukaimasu",
    clusterId: "c1",
    iconName: "hammer",
  },

  {
    id: "4",
    lessonId: "lesson_15",
    kana: "おきます",
    kanji: "置きます",
    meaning: "Đặt, để",
    romaji: "okimasu",
    clusterId: "c1",
    iconName: "package",
  },

  {
    id: "5",
    lessonId: "lesson_15",
    kana: "つくります",
    kanji: "作ります・造ります",
    meaning: "Làm, chế tạo, sản xuất",
    romaji: "tsukurimasu",
    clusterId: "c1",
    iconName: "wrench",
  },

  {
    id: "6",
    lessonId: "lesson_15",
    kana: "うります",
    kanji: "売ります",
    meaning: "Bán",
    romaji: "urimasu",
    clusterId: "c1",
    iconName: "store",
  },

  {
    id: "7",
    lessonId: "lesson_15",
    kana: "しります",
    kanji: "知ります",
    meaning: "Biết",
    romaji: "shirimasu",
    clusterId: "c1",
    iconName: "brain",
  },

  {
    id: "8",
    lessonId: "lesson_15",
    kana: "すみます",
    kanji: "住みます",
    meaning: "Sống, ở",
    romaji: "sumimasu",
    clusterId: "c1",
    iconName: "house",
  },

  {
    id: "9",
    lessonId: "lesson_15",
    kana: "けんきゅうします",
    kanji: "研究します",
    meaning: "Nghiên cứu",
    romaji: "kenkyuu shimasu",
    clusterId: "c1",
    iconName: "microscope",
  },

  {
    id: "10",
    lessonId: "lesson_15",
    kana: "しっています",
    kanji: "知っています",
    meaning: "Biết",
    romaji: "shitte imasu",
    clusterId: "c1",
    iconName: "lightbulb",
  },

  {
    id: "11",
    lessonId: "lesson_15",
    kana: "すんでいます",
    kanji: "住んでいます",
    meaning: "Đang sống, đang ở",
    romaji: "sunde imasu",
    clusterId: "c2",
    iconName: "building-2",
  },

  {
    id: "12",
    lessonId: "lesson_15",
    kana: "しりょう",
    kanji: "資料",
    meaning: "Tài liệu, tư liệu",
    romaji: "shiryou",
    clusterId: "c2",
    iconName: "file-text",
  },

  {
    id: "13",
    lessonId: "lesson_15",
    kana: "カタログ",
    kanji: "",
    meaning: "Ca-ta-lô",
    romaji: "katarogu",
    clusterId: "c2",
    iconName: "book-open",
  },

  {
    id: "14",
    lessonId: "lesson_15",
    kana: "じこくひょう",
    kanji: "時刻表",
    meaning: "Bảng giờ tàu chạy",
    romaji: "jikokuhyou",
    clusterId: "c2",
    iconName: "clock",
  },

  {
    id: "15",
    lessonId: "lesson_15",
    kana: "ふく",
    kanji: "服",
    meaning: "Quần áo",
    romaji: "fuku",
    clusterId: "c2",
    iconName: "shirt",
  },

  {
    id: "16",
    lessonId: "lesson_15",
    kana: "せいひん",
    kanji: "製品",
    meaning: "Sản phẩm",
    romaji: "seihin",
    clusterId: "c2",
    iconName: "package-check",
  },

  {
    id: "17",
    lessonId: "lesson_15",
    kana: "ソフト",
    kanji: "",
    meaning: "Phần mềm",
    romaji: "sofuto",
    clusterId: "c2",
    iconName: "laptop",
  },

  {
    id: "18",
    lessonId: "lesson_15",
    kana: "せんもん",
    kanji: "専門",
    meaning: "Chuyên môn",
    romaji: "senmon",
    clusterId: "c2",
    iconName: "graduation-cap",
  },

  {
    id: "19",
    lessonId: "lesson_15",
    kana: "はいしゃ",
    kanji: "歯医者",
    meaning: "Nha sĩ",
    romaji: "haisha",
    clusterId: "c2",
    iconName: "badge-plus",
  },

  {
    id: "20",
    lessonId: "lesson_15",
    kana: "とこや",
    kanji: "床屋",
    meaning: "Hiệu cắt tóc",
    romaji: "tokoya",
    clusterId: "c2",
    iconName: "scissors",
  },

  {
    id: "21",
    lessonId: "lesson_15",
    kana: "プレイガイド",
    kanji: "",
    meaning: "Quầy bán vé",
    romaji: "pureigaido",
    clusterId: "c3",
    iconName: "ticket",
  },

  {
    id: "22",
    lessonId: "lesson_15",
    kana: "どくしん",
    kanji: "独身",
    meaning: "Độc thân",
    romaji: "dokushin",
    clusterId: "c3",
    iconName: "user",
  },

  {
    id: "23",
    lessonId: "lesson_15",
    kana: "とくに",
    kanji: "特に",
    meaning: "Đặc biệt",
    romaji: "tokuni",
    clusterId: "c3",
    iconName: "star",
  },

  {
    id: "24",
    lessonId: "lesson_15",
    kana: "おもいだします",
    kanji: "思い出します",
    meaning: "Nhớ lại, hồi tưởng",
    romaji: "omoidashimasu",
    clusterId: "c3",
    iconName: "history",
  },

  {
    id: "25",
    lessonId: "lesson_15",
    kana: "ごかぞく",
    kanji: "ご家族",
    meaning: "Gia đình (của người khác)",
    romaji: "gokazoku",
    clusterId: "c3",
    iconName: "users",
  },

  {
    id: "26",
    lessonId: "lesson_15",
    kana: "いらっしゃいます",
    kanji: "",
    meaning: "Có mặt, ở (kính ngữ của います)",
    romaji: "irasshaimasu",
    clusterId: "c3",
    iconName: "crown",
  },

  {
    id: "27",
    lessonId: "lesson_15",
    kana: "こうこう",
    kanji: "高校",
    meaning: "Trường trung học phổ thông",
    romaji: "koukou",
    clusterId: "c3",
    iconName: "school",
  },
];